standard:
  devices: 3
  days_options:
  - days: 30
    price_rub: 300.0
    price_usdt: 5.0
  - days: 90
    price_rub: 600.0
    price_usdt: 9.0
  - days: 180
    price_rub: 999.0
    price_usdt: 15.0
  - days: 365
    price_rub: 1799.0
    price_usdt: 27.0
extended:
  devices: 10
  days_options:
  - days: 30
    price_rub: 499
    price_usdt: 5.5
  - days: 90
    price_rub: 1299
    price_usdt: 14.5
  - days: 180
    price_rub: 2299
    price_usdt: 25.5
  - days: 365
    price_rub: 3999
    price_usdt: 44.5
trial:
  days: 3
  devices: 3
referral:
  inviter_bonus_days: 7
  invitee_bonus_days: 3
squads:
  standard: []
  extended: []
  trial: []
